function getData(dataID , getNextData){
    //2s delay
    setTimeout(()=>{
        console.log("data",dataID);

        if(getNextData){
            getNextData();
        }
    },2000);
}
//callback hell
getData(1,()=>{
    getData(2,()=>{
        getData(3,()=>{
            getData(4,()=>{
                getData(5,()=>{
                    getData(6,()=>{
                        getData(7,()=>{
                            getData(8,()=>{
                                getData(9,()=>{
                                    getData(10,()=>{
                                        getData(11,()=>{
                                            getData(12,()=>{
                                                getData(13,()=>{
                                                    getData(14,()=>{
                                                        getData(15,()=>{
                                                            getData(16,()=>{
                                                                getData(17,()=>{
                                                                    getData(18,()=>{
                                                                        getData(19,()=>{
                                                                            getData(20,()=>{
                                                                                getData(21,()=>{
                                                                                    getData(22,()=>{
                                                                                        getData(23,()=>{
                                                                                            getData(24,()=>{
                                                                                                getData(25,()=>{
                                                                                                    getData(26,()=>{
                                                                                                        getData(27,()=>{
                                                                                                            getData(28,()=>{
                                                                                                                getData(29,()=>{
                                                                                                                    getData(30,()=>{
                                                                                                                        getData(31,()=>{
                                                                                                                            getData(32,()=>{
                                                                                                                                getData(33,()=>{
                                                                                                                                    getData(34,()=>{
                                                                                                                                        getData(35,()=>{
                                                                                                                                            getData(36,()=>{
                                                                                                                                                getData(37,()=>{
                                                                                                                                                    getData(38,()=>{
                                                                                                                                                        getData(39,()=>{
                                                                                                                                                                                       getData(40,()=>{
                                                                                                                                console.log("done");
                                                                                                                                                                                                                                });
                                                                                                                                                                                                                            });
                                                                                                                                                                                                                        });
                                                                                                                                                                                                                    });
                                                                                                                                                                                                                });
                                                                                                                                                                                                            });
                                                                                                                                                                                                        });
                                                                                                                                                                                                    });
                                                                                                                                                                                                });
                                                                                                                                                                                            });
                                                                                                                                                                                        });
                                                                                                                                                                                    });
                                                                                                                                                                                });
                                                                                                                                                                            });
                                                                                                                                                                        });
                                                                                                                                                                    });
                                                                                                                                                                });
                                                                                                                                                            });
                                                                                                                                                        });
                                                                                                                                                    });
                                                                                                                                                });
                                                                                                                                            });
                                                                                                                                        });
                                                                                                                                    });
                                                                                                                                });
                                                                                                                            });
                                                                                                                        });
                                                                                                                    });
                                                                                                                });
                                                                                                            });
                                                                                                        });
});